version: "3"
services:
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crash_archive
    volumes:
      - dbdata:/var/lib/mysql
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/Dockerfile-app
    ports:
      - "8080:80"
    volumes:
      - ./templates:/app/templates
      - ./assets:/app/assets
      - ./config.json:/app/config.json
      - reportdata:/reports
volumes:
  dbdata:
  reportdata:
